NUMBER=0

example:
	yes | ../../bin/mimic copy \
	-v "number=$$(echo ${NUMBER})" \
	-v "number_x_1=$$((${NUMBER} * 1))" \
	-v "number_x_2=$$((${NUMBER} * 2))" \
	-v "number_x_3=$$((${NUMBER} * 3))" \
	-v "number_x_4=$$((${NUMBER} * 4))" \
	-v "number_x_5=$$((${NUMBER} * 5))" \
	-v "number_x_6=$$((${NUMBER} * 6))" \
	-v "number_x_7=$$((${NUMBER} * 7))" \
	-v "number_x_8=$$((${NUMBER} * 8))" \
	-v "number_x_9=$$((${NUMBER} * 9))" \
	-v "number_x_10=$$((${NUMBER} * 10))" \
	-s "./multiplication_table_of_{{number}}.md.mimic" \
	--debug