.SILENT:
example:
	yes | ../../bin/mimic \
	--debug \
	-p name="What is your name? " \
	-p age="What is your age? " \
	-p country="Where are you from? " \
	-p bio="Who are you? " \
	-v name="Foo Bar Baz" \
	-v age=22 \
	-v country="Brazil" \
	-v bio="I am a software engineer." \
	\{\{pascal\(name\)\}\}.md.mimic .
